xcopy E:\hongjing\edit\Texture\Common\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Fire\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Flash\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Fluxay\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Glow\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Lightning\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Object\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Other\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Pattern\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Quest\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Ring\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Rotation\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\self\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Sequence\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Smoke\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Spot\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Star\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Trail\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\Water\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\zyh\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s
xcopy E:\hongjing\edit\Texture\ui\*.png E:\client\project\tool\ParticleSourceCopy\game\res\eft\texture /s

xcopy E:\hongjing\edit\mesh\*.mesh E:\client\project\tool\ParticleSourceCopy\game\res\eft\mesh /s
xcopy E:\hongjing\edit\fu\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\ui\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\jineng\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\Skill\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\buff\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\zcxg\*.xml E:\client\project\tool\ParticleSourceCopy\game\res\eft\work_script /s
xcopy E:\hongjing\edit\mesh\*.skeleton E:\client\project\tool\ParticleSourceCopy\game\res\eft\mesh /s
